services:

  userportal:
    build:
      context: ./UserPortal/UserPortal
      dockerfile: Dockerfile
    ports:
      - "6888:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - MongoDB__ConnectionString=mongodb://mongodb:27017
      - MongoDB__DatabaseName=UserPortalDb
    depends_on:
      - mongodb

  bankportal:
    build:
      context: ./BankPortal/BankPortal
      dockerfile: Dockerfile
    ports:
      - "7888:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - MongoDB__ConnectionString=mongodb://mongodb:27017
      - MongoDB__DatabaseName=BankPortalDb
    depends_on:
      - mongodb

  tokenportal:
    build:
      context: ./TokenPortal/TokenPortal
      dockerfile: Dockerfile
    ports:
      - "8888:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - MongoDB__ConnectionString=mongodb://mongodb:27017
      - MongoDB__DatabaseName=TokenPortalDb
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
